<a href="https://colab.research.google.com/github/hongseoi/colab/blob/main/0720%ED%95%A8%EC%88%98%EC%A0%95%EB%A6%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

<img src="https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FF2bI1%2FbtqJSciC5nJ%2FstSwF20OKLLuCSzvVz68fk%2Fimg.png">

```
# 코드로 형식 지정됨
```



In [ ]:
#Conv1D()
## 합성곱 연산 기능 중 한방향(가로)로 합성곱. 1dArray 즉 벡터 출력
## 주로 이미지 데이터를 사용하는 인공신경망에서 사용함
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

input_size = (1,28,28)
input = tf.placeholder(tf.float32, shape=input_size)
conv = tf.keras.layers.Conv1D(
    filters = 10,
    kernel_size = 3,
    padding = 'same',
    activation = tf.nn.relu
)(input)

Instructions for updating:
non-resource variables are not supported in the long term


Instructions for updating:
non-resource variables are not supported in the long term


##RNN(Recurrent Neural Network)
* 스스로를 반복하며 이전 단계에서 얻은 정보가 지속되도록 함
* 음성인식, 언어 모델링, 번역, 이미지 주석 등 다양한 분야에서 사용됨
* 긴 의존기간의 문제: 필요한 정보를 얻기위한 시간 격차가 커질수록 어려워진다.

##LSTM(Long Short Term Memory)
* rnn 성공의 열쇠
* 특별한 종류의 RNN: 긴 의존기간을 필요로 하는 학습 수행 가능
* 

참고: https://dgkim5360.tistory.com/entry/understanding-long-short-term-memory-lstm-kr

In [ ]:
#LSTM 간단한 예제

from numpy import array
from keras.models import Sequential
from keras.layers import Dense, LSTM

x = array([[1,2,3],[2,3,4],[3,4,5],[4,5,6]])
y = array([4,5,6,7])

print('x shape:',x.shape)
print('y shape:', y.shape)
print(x)

print('-----------x reshape----------------')
x = x.reshape((x.shape[0],x.shape[1],1))
print('x shape:', x.shape)
print(x)

# 모델 구성
model = Sequential()
model.add(LSTM(10, activation='relu', input_shape=(3,1)))
model.add(Dense(5))
model.add(Dense(1))

model.summary()

model.compile(optimizer='adam', loss='mse')
model.fit(x,y,epochs=100, batch_size=1)

x_input = array([6,7,8])
x_input = x_input.reshape((1,3,1))

yhat = model.predict(x_input)
print(yhat)

x shape: (4, 3)
y shape: (4,)
[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]
-----------x reshape----------------
x shape: (4, 3, 1)
[[[1]
  [2]
  [3]]

 [[2]
  [3]
  [4]]

 [[3]
  [4]
  [5]]

 [[4]
  [5]
  [6]]]
Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_1 (LSTM)               (None, 10)                480       
                                                                 
 dense_2 (Dense)             (None, 5)                 55        
                                                                 
 dense_3 (Dense)             (None, 1)                 6         
                                                                 
Total params: 541
Trainable params: 541
Non-trainable params: 0
_________________________________________________________________
Train on 4 samples
Epoch 1/100
4/4 [==============================] - 0s 3ms/sample - loss: 29.1832
Epoch 2/100
4/4 [

/usr/local/lib/python3.7/dist-packages/keras/engine/training_v1.py:2079: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  updates=self.state_updates,


In [ ]:
'''
# 차원확장
tf.expand_dims(
    input = 
    axis = 
    name = None
)

'''



In [ ]:
# from_tensor_slices: numpy array나 list를 tensor dataset으로 변환

x = tf.placeholder(tf.float32, shape=[None, 2])
dataset = tf.data.Dataset.from_tensor_slices(x)

In [ ]:
#suffle():리스트 멤버 섞기
import random 
lst = [x for x in range(1,10)]
print(lst)

random.shuffle(lst)
print(lst)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[2, 4, 7, 8, 6, 5, 1, 9, 3]


In [ ]:
#batch

import keras
from keras.optimizer import SGD

# Instantiate an optimizer.
optimizer = keras.optimizers.SGD(learning_rate=1e-3)
# Instantiate a loss function.
loss_fn = keras.losses.SparseCategoricalCrossentropy(from_logits=True)

# Prepare the training dataset.
batch_size = 64
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()
x_train = np.reshape(x_train, (-1, 784))
x_test = np.reshape(x_test, (-1, 784))

# Reserve 10,000 samples for validation.
x_val = x_train[-10000:]
y_val = y_train[-10000:]
x_train = x_train[:-10000]
y_train = y_train[:-10000]

# Prepare the training dataset.
train_dataset = tf.data.Dataset.from_tensor_slices((x_train, y_train))
train_dataset = train_dataset.shuffle(buffer_size=1024).batch(batch_size)

# Prepare the validation dataset.
val_dataset = tf.data.Dataset.from_tensor_slices((x_val, y_val))
val_dataset = val_dataset.batch(batch_size)

ModuleNotFoundError: ignored

In [ ]:
#prefetch
'''
훈련속도 더 빠르게
prefetch(1) 호출하면 데이터셋은 항상 한 배치가 미리 준비되도록 함

'''

In [ ]:
# window