In [1]:
import pandas as pd
data_url = "https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data"

df_data = pd.read_csv(data_url, sep="\s+", header=None)

df_data.columns = ['CRIM','ZN','INDUS','CHAS','NOX','RM','AGE','DIS','RAD','TAX','PTRATIO','B','LSTAT','MEDV']
df_data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [2]:
import numpy as np
df_data['weight_0'] = 1
df_data = df_data.drop("MEDV", axis=1)
df_matrix = df_data.values
weight_vector = np.random.random_sample((14,1))
df_matrix.dot(weight_vector)

array([[449.27695941],
       [402.62705176],
       [398.19016475],
       [379.42232852],
       [381.8565283 ],
       [380.83121001],
       [459.6660119 ],
       [464.66439207],
       [460.10784295],
       [458.08554678],
       [462.38794715],
       [462.71024599],
       [453.29636161],
       [449.43226537],
       [443.94957719],
       [447.99211409],
       [440.15857654],
       [447.18105553],
       [390.69818589],
       [447.39964098],
       [444.60898511],
       [451.17136036],
       [454.24603925],
       [453.90654654],
       [452.76827871],
       [405.08599826],
       [443.22403918],
       [407.26199036],
       [449.63875294],
       [444.92787939],
       [435.68463045],
       [445.06702084],
       [369.07713204],
       [434.953454  ],
       [379.22427656],
       [427.18446823],
       [416.39626436],
       [423.5867136 ],
       [420.39356169],
       [457.96103495],
       [457.19867668],
       [379.9748002 ],
       [379.31984394],
       [385

In [3]:
import numpy as np
test_array = np.array([1,4,5,8], float)
test_array


array([1., 4., 5., 8.])

In [4]:
type(test_array)

numpy.ndarray

In [5]:
type(test_array[0])

numpy.float64

In [8]:
test_array = np.array([1,3,4,"8"],float)
test_array

array([1., 3., 4., 8.])

In [9]:
print(type(test_array[3]))

<class 'numpy.float64'>


In [11]:
test_array.shape

(4,)

In [12]:
test_array2 = np.array([[1,4,5,8],[1,4,5,8]])
test_array2.shape

(2, 4)

In [15]:
test_array3 = np.array([test_array*2])
test_array3

array([[ 2.,  6.,  8., 16.]])

In [44]:
tensor_rank4 = np.array([[
                [[1,2,5,8], [1,2,5,8],[1,2,5,8]],
                [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
                [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
                [[1,2,5,8],[1,2,5,8],[1,2,5,8]]
],
[
                [[1,2,5,8], [1,2,5,8],[1,2,5,8]],
                [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
                [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
                [[1,2,5,8],[1,2,5,8],[1,2,5,8]]
]])

tensor_rank4.shape


(2, 4, 3, 4)

In [45]:
tensor_rank5 = [[[
                [[1,2,5,8], [1,2,5,8],[1,2,5,8]],
                [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
                [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
                [[1,2,5,8],[1,2,5,8],[1,2,5,8]]
],
[
                [[1,2,5,8], [1,2,5,8],[1,2,5,8]],
                [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
                [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
                [[1,2,5,8],[1,2,5,8],[1,2,5,8]]
]]]

np.array(tensor_rank5, int).shape

(1, 2, 4, 3, 4)

In [30]:
array = np.array([[1,2,3.5],[4,5,6.5]], dtype=float)
np.round(array)


array([[1., 2., 4.],
       [4., 5., 6.]])

In [32]:
x = np.array([[1,2,5,8],[1,2,5,8]])
x.shape

(2, 4)

In [33]:
x.reshape(-1,)

array([1, 2, 5, 8, 1, 2, 5, 8])

In [34]:
x.reshape(4,-1)

array([[1, 2],
       [5, 8],
       [1, 2],
       [5, 8]])

In [49]:
x.reshape(1,-1)

array([[1, 2, 5, 8, 1, 2, 5, 8]])

In [57]:
a = x.reshape(-1)
a

array([1, 2, 5, 8, 1, 2, 5, 8])

In [58]:
a.T

array([1, 2, 5, 8, 1, 2, 5, 8])

In [46]:
tensor_rank4.reshape(8,4,-1)

array([[[1, 2, 5],
        [8, 1, 2],
        [5, 8, 1],
        [2, 5, 8]],

       [[1, 2, 5],
        [8, 1, 2],
        [5, 8, 1],
        [2, 5, 8]],

       [[1, 2, 5],
        [8, 1, 2],
        [5, 8, 1],
        [2, 5, 8]],

       [[1, 2, 5],
        [8, 1, 2],
        [5, 8, 1],
        [2, 5, 8]],

       [[1, 2, 5],
        [8, 1, 2],
        [5, 8, 1],
        [2, 5, 8]],

       [[1, 2, 5],
        [8, 1, 2],
        [5, 8, 1],
        [2, 5, 8]],

       [[1, 2, 5],
        [8, 1, 2],
        [5, 8, 1],
        [2, 5, 8]],

       [[1, 2, 5],
        [8, 1, 2],
        [5, 8, 1],
        [2, 5, 8]]])

In [47]:
tensor_rank4.reshape(8,2,-1)

array([[[1, 2, 5, 8, 1, 2],
        [5, 8, 1, 2, 5, 8]],

       [[1, 2, 5, 8, 1, 2],
        [5, 8, 1, 2, 5, 8]],

       [[1, 2, 5, 8, 1, 2],
        [5, 8, 1, 2, 5, 8]],

       [[1, 2, 5, 8, 1, 2],
        [5, 8, 1, 2, 5, 8]],

       [[1, 2, 5, 8, 1, 2],
        [5, 8, 1, 2, 5, 8]],

       [[1, 2, 5, 8, 1, 2],
        [5, 8, 1, 2, 5, 8]],

       [[1, 2, 5, 8, 1, 2],
        [5, 8, 1, 2, 5, 8]],

       [[1, 2, 5, 8, 1, 2],
        [5, 8, 1, 2, 5, 8]]])

In [52]:
re_x = x.reshape(2,2,-1)
print(re_x.shape, re_x.ndim, re_x.size)

(2, 2, 2) 3 8


In [53]:
x.flatten() #다 1차원으로

array([1, 2, 5, 8, 1, 2, 5, 8])

In [60]:
x = np.array(range(8)).reshape(2,2,2)
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [61]:
x = np.array([[1,2,3],[4.5,5,6]], int)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
x[0][0]

1

In [63]:
x[0,2]

3

In [64]:
x[0,1] == 100
x

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
# 슬라이싱
x = np.array([[1,2,3,4,5], [6,7,8,9,10]], int)
x[:,2:]

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [66]:
x[1,1:3]

array([7, 8])

In [67]:
x[1:3]

array([[ 6,  7,  8,  9, 10]])

In [69]:
x = np.array(range(15), int).reshape(3,-1)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [70]:
x[:,::2]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14]])

In [71]:
x[::2, ::3]

array([[ 0,  3],
       [10, 13]])