In [1]:
import numpy as np
x = np.array([[1,2,5,8],[1,2,5,8],[1,2,5,8],[1,2,5,8]])
x

array([[1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8]])

In [2]:
x[:2,:]

array([[1, 2, 5, 8],
       [1, 2, 5, 8]])

In [4]:
x[1,1:3] #1행만 의미

array([2, 5])

In [5]:
x[1:3] #행에 대한 것만

array([[1, 2, 5, 8],
       [1, 2, 5, 8]])

In [7]:
x = np.array(range(15), int).reshape(3,-1)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [8]:
x[:,::2]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14]])

In [9]:
x[::2, ::3]

array([[ 0,  3],
       [10, 13]])

In [10]:
x[1,2]

7

In [11]:
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [16]:
np.arange(30,10,-5)

array([30, 25, 20, 15])

In [17]:
np.arange(30,10,-3.5)

array([30. , 26.5, 23. , 19.5, 16. , 12.5])

In [20]:
np.ones(shape=(5,2), dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [24]:
np.eye(N=3, M=5, k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
matrix = np.arange(9).reshape(3,3)
np.diag(matrix)

array([0, 4, 8])

In [27]:
np.diag(matrix, k=-1)

array([3, 7])

In [28]:
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [29]:
np.random.uniform(0,5,10) #시작값 ,끝값, 데이터개수

array([3.8482708 , 0.84773921, 3.07289715, 3.7591332 , 0.53564282,
       2.84468184, 1.62564098, 2.40602844, 3.92727629, 1.74410402])

In [35]:
a = np.arange(1, 13).reshape(3,4)
b = np.array([a,a])
b

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [36]:
b.sum(axis=0)

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [37]:
b.sum(axis=1)

array([[15, 18, 21, 24],
       [15, 18, 21, 24]])

In [38]:
b.sum(axis=2)

array([[10, 26, 42],
       [10, 26, 42]])

In [40]:
for i in range(3):
  print("axis=",i)
  print(b.sum(axis=i))

axis= 0
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
axis= 1
[[15 18 21 24]
 [15 18 21 24]]
axis= 2
[[10 26 42]
 [10 26 42]]


In [41]:
c = np.array([
              [[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]],
        [[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]]
])

c

array([[[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]],


       [[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]]])

In [46]:
c.shape

(2, 2, 3, 4)

In [42]:
c.sum(axis=0)

array([[[ 2,  4,  6,  8],
        [10, 12, 14, 16],
        [18, 20, 22, 24]],

       [[ 2,  4,  6,  8],
        [10, 12, 14, 16],
        [18, 20, 22, 24]]])

In [43]:
c.sum(axis=1)

array([[[ 2,  4,  6,  8],
        [10, 12, 14, 16],
        [18, 20, 22, 24]],

       [[ 2,  4,  6,  8],
        [10, 12, 14, 16],
        [18, 20, 22, 24]]])

In [44]:
c.sum(axis=2)

array([[[15, 18, 21, 24],
        [15, 18, 21, 24]],

       [[15, 18, 21, 24],
        [15, 18, 21, 24]]])

In [45]:
c.sum(axis=3)

array([[[10, 26, 42],
        [10, 26, 42]],

       [[10, 26, 42],
        [10, 26, 42]]])

In [49]:
x1 = np.arange(1,13).reshape(3,4)
x2 = np.arange(11,23).reshape(3,4)
x3 = np.arange(21,33).reshape(3,4)
x4 = np.arange(31, 43).reshape(3,4)

x = np.array([[x1,x2],[x3,x4]])
x

array([[[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[11, 12, 13, 14],
         [15, 16, 17, 18],
         [19, 20, 21, 22]]],


       [[[21, 22, 23, 24],
         [25, 26, 27, 28],
         [29, 30, 31, 32]],

        [[31, 32, 33, 34],
         [35, 36, 37, 38],
         [39, 40, 41, 42]]]])

In [51]:
for i in range(3):
  print("axis=",i,"-----------------")
  print(x.sum(axis=i))

axis= 0 -----------------
[[[22 24 26 28]
  [30 32 34 36]
  [38 40 42 44]]

 [[42 44 46 48]
  [50 52 54 56]
  [58 60 62 64]]]
axis= 1 -----------------
[[[12 14 16 18]
  [20 22 24 26]
  [28 30 32 34]]

 [[52 54 56 58]
  [60 62 64 66]
  [68 70 72 74]]]
axis= 2 -----------------
[[[ 15  18  21  24]
  [ 45  48  51  54]]

 [[ 75  78  81  84]
  [105 108 111 114]]]


In [52]:
x = np.array([4,5,6,7,3,2])
x>3

array([ True,  True,  True,  True, False, False])

In [53]:
(x>3).all()

False

In [54]:
(x>3).any()

True

In [56]:
x = np.array([4,6,7,3,2])
np.argsort(x)

array([4, 3, 0, 1, 2])

In [57]:
np.argmax(x)

2

In [58]:
np.argmin(x)

4